title: Style Guide WIP
description: (What are you doing here? This is still a work in progress!)
url: https://alexakreizinger.github.io #theme breaks without this?
baseurl: /styleguide #theme breaks without this?

remote_theme: just-the-docs/just-the-docs
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
# for more options, consult https://just-the-docs.github.io/just-the-docs/docs/search/

collections_dir: audiences #sets the collections folder location
collections: #stored in the `audiences` folder
  techdocs: #make sure the corresponding folder starts with an underscore (e.g., _techdocs)
    output: true
    permalink: /:collection/:path/
  marketing:
    output: true
    permalink: /:collection/:path/
  dev:
    output: true
    permalink: /:collection/:path/
  all:
    output: true
    permalink: /:collection/:path/

plugins:
  - liquify