theme: jekyll-theme-minimal
title: Style Guide WIP
description: (What are you doing here? This is still a work in progress!)
baseurl: "https://alexakreizinger.github.io/styleguide"

collections:
  all:
    output: true
