theme: jekyll-theme-minimal
title: Style Guide WIP
description: (What are you doing here? This is still a work in progress!)
url: https://alexakreizinger.github.io
baseurl: /styleguide

collections:
  all:
    output: true
